# Bagian 4 - NumPy N-dimensional Array
Array merupakan struktur data utama yang digunakan di machine learning. Di python, array dari NumPy library disebut N-dimensional array atau ndarray yang digunakan secara umum untuk struktur data dalam merepresentasikan bilangan dan manipulasi data di python.

## Fungsi untuk membuat array

### Example

In [3]:
# import
from numpy import array

# create array
l = [1.0, 2.0, 3.0]
a = array(l)

# display array
print(a)

# display array shape
print(a.shape)

#display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


### 1. Empty()
Fungsi empty akan membuat array baru dengan bentuk yang spesifik. Argumen dari array menyebutkan spesifikasi luas dimensi dari array yang dibuat. Nilai yang akan dibuat pada array bakalan secara acak.

In [4]:
# create empty array
from numpy import empty

a = empty([3,3])
print(a)

[[4.68842392e-310 1.63041663e-322 0.00000000e+000]
 [            nan 4.68842375e-310 0.00000000e+000]
 [0.00000000e+000             nan 7.11454530e-322]]


### 2. Zeros()
fungsi zeros() akan membuat array dengan luas yang spesifik dengan mengisi nilai 0

In [1]:
# create zero array
from numpy import zeros

a = zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 3. Ones()
fungsi ones() akan membuat array dengan luas dimensi yang spesifik dengan mengisi nilai 1

In [4]:
# create ones array
from numpy import ones

a = ones([3,5])
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Menyusun Array

### 1. Vertical Stack
menyusun secara vertikal (atas ke bawah) 2 atau lebih array menggunakan fungsi vstack()

In [70]:
# create array with vstack
from numpy import array
from numpy import vstack

#create first array
a1 = array([4,5,6])
print(a1)

# create second array
a2 = array([6,7,8])
print(a2)

# create vertical stack
a3 = vstack((a1,a2))
print(a3)
print(a3.dtype)
print(a3.shape)


[4 5 6]
[6 7 8]
[[4 5 6]
 [6 7 8]]
int64
(2, 3)


### 2. Horizontal Stack
Menyusun secara horizontal (kiri ke kanan) dari 2 atau lebih array yang sudah ada menggunakan hstack

In [7]:
# create array with vstack
from numpy import array
from numpy import hstack

#create first array
a1 = array([4,5,6])
print(a1)

# create second array
a2 = array([6,7,8])
print(a2)

# create vertical stack
a3 = hstack((a1,a2))
print(a3)
print(a3.dtype)
print(a3.shape)


[4 5 6]
[6 7 8]
[4 5 6 6 7 8]
int64
(6,)


## Bagian 5 - Index, Slice and Reshape NumPy Arrays
Data di machine learning direpresentasikan sebagai array. Pada bagian ini akan dibahas bagaimana mengakses, memanipulasi data secara benar didalm NumPy arrays.

### From list to arrays

#### One-Dimensional List to Array

In [9]:
# creata one-dimensional array
from numpy import array

# list of data
data = [11,22,33,44,55]

# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


#### Two-Dimensional List to Array

In [10]:
# creata two-dimensional array
from numpy import array

# list of data
data = [[11,22],[33,44],[55,66]]

# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


### Array Indexing

#### one-dimensional indexing

In [13]:
# creata two-dimensional array
from numpy import array

# list of data
data = array([22,11,33,44])

# index data
print(data[0])
print(data[3])
print(data[-1])

22
44
44


#### two-dimensional indexing

In [20]:
# creata two-dimensional array
from numpy import array

# list of data
data = array([[22,11],[33,44],[77,88]])

# index data
print(data[1,0])
print(data[0,])

33
[22 11]


### Array Slicing
data[from:to]

#### one-dimensional slicing

In [27]:
# creata two-dimensional array
from numpy import array

# list of data
data = array([22,11,33,44])
print(data[:]) # with no indexes
print(data[1:]) # start index 1 end in last index
print(data[:1]) # start first index end in second index
print(data[-2:]) # start -2 index end in last index

[22 11 33 44]
[11 33 44]
[22]
[33 44]


#### two-dimensional slicing

**Split input and output features**
Untuk fitur input, kita dapat memilih semua baris dan semua kolom kecuali yang terakhir dengan **menetapkan : untuk dalam indeks baris**, dan **: -1 dalam indeks kolom.**

X = [:, :-1]

Untuk kolom output, kita dapat memilih semua baris lagi menggunakan : dan indeks hanya kolom terakhir dengan menentukan indeks -1.

y = [:, -1]

Menempatkan semua ini bersama-sama, kita dapat memisahkan dataset 2D 3-kolom ke input dan output data sebagai berikut:

In [42]:
# split input dan output
from numpy import array

# define array
data = array([[11,22,33],
              [44,55,66],
              [77,88,99]])

# separate data
X,y = data[:, :-1], data[:,-1]

print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


**Split Train and Test Rows**

Data latih akan dimulai dari awal hingga titik _split_.
train = data[:split, :]

Data tes akan dimulai dari titk _split_ hingga akhir array
test = data[split:, :]

In [44]:
# split train and test data
from numpy import array

# define array
data = array([[11,22,33],
             [44,55,66],
             [77,88,99]])

# separate data
# remember data[from:to]
split = 2
train,test = data[:split, :], data[split:, :]

print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


### Array Reshaping
Setelah melakukan slicing pada array, mungkin kita membutuhkan reshape (pembentukan ulang).

#### Data Shape
NumPy array memiliki atribut **shape** yang mengembalikan panjang nilai array dari setiap dimensi array

In [50]:
# shape of one-dimensional array
from numpy import array

# define array
data = array([11,22,33,44,55])
print(data.shape)

(5,)


In [46]:
# shape of two-dimensional array
from numpy import array

# define array
data = array([[11,22],[33,44],[55,66]])
print(data.shape)

(3, 2)


In [52]:
# row and column shape of two-dimensional array
from numpy import array

# define array
data = [[11,22],[33,44],[55,66]]

#array of data
data = array(data)
print('Kolom : %d' % data.shape[0])
print('Baris : %d' % data.shape[1])

Kolom : 3
Baris : 2


#### Reshape 1D to 2D Array
ketika dibutuhkan pembentukan ulang array 1 dimensi di ubah ke array 2 dimensi dengan 1 kolom dan beberapa array. NumPy menyediakan fungsi **reshape()** pada objek array NumPy yang akan digunakan untuk mengubah bentuk data.

`data = data.reshape(data.shape[0],1)`

In [55]:
# reshape 1D array to 2D
from numpy import array

# Define array
data = array([11,22,33,44,55])
print(data.shape)
print(data)

# reshape
data = data.reshape(data.shape[0],1)
print(data.shape)
print(data)

(5,)
[11 22 33 44 55]
(5, 1)
[[11]
 [22]
 [33]
 [44]
 [55]]


#### Reshape 2D to 3D Array

`data = data.reshape(data.shape[0],data.shape[1], 1)`

In [59]:
# reshape 2D array to 3D
from numpy import array

# list of data
data = [[11,22],
       [33,44],
       [55,66],
       [77,88]]

# array of data
data = array(data)
print(data.shape)

# reshape
data = data.reshape(data.shape[0], data.shape[1], 1)
print(data.shape)

(4, 2)
(4, 2, 1)


#### Extension

In [106]:
import csv

with open('DataSet/winequality-white.csv', 'r') as f:
    wines = list(csv.reader(f, delimiter=';'))

print(wines.shape)

AttributeError: 'list' object has no attribute 'shape'